export type EducationBoard = {
  id: string
  abbr: string
  name: string
  levels?: string
  note?: string
}

export type BoardRegion = 'all' | 'india' | 'international' | 'asia-pacific' | 'europe' | 'americas' | 'middle-east' | 'africa'

export type CountryBoards = {
  id: string
  country: string
  flag: string
  region: Exclude<BoardRegion, 'all'>
  accent: string
  ring: string
  chipBg: string
  boards: EducationBoard[]
}

export const boardRegions: { id: BoardRegion; label: string; icon: string }[] = [
  { id: 'all', label: 'All regions', icon: 'mdi:earth' },
  { id: 'india', label: 'India', icon: 'mdi:flag' },
  { id: 'international', label: 'International', icon: 'mdi:web' },
  { id: 'asia-pacific', label: 'Asia-Pacific', icon: 'mdi:asia' },
  { id: 'europe', label: 'Europe', icon: 'mdi:earth-europe' },
  { id: 'americas', label: 'Americas', icon: 'mdi:earth-americas' },
  { id: 'middle-east', label: 'Middle East', icon: 'mdi:mosque' },
  { id: 'africa', label: 'Africa', icon: 'mdi:earth-africa' },
]

export const countriesByBoards: CountryBoards[] = [
  {
    id: 'india',
    country: 'India',
    flag: '🇮🇳',
    region: 'india',
    accent: 'from-orange-500 to-amber-600',
    ring: 'ring-orange-200',
    chipBg: 'bg-orange-50 text-orange-900 ring-orange-100',
    boards: [
      { id: 'cbse', abbr: 'CBSE', name: 'Central Board of Secondary Education', levels: 'Class 1–12' },
      { id: 'icse', abbr: 'ICSE', name: 'Indian Certificate of Secondary Education (CISCE)', levels: 'Class 1–10' },
      { id: 'isc', abbr: 'ISC', name: 'Indian School Certificate (CISCE)', levels: 'Class 11–12' },
      { id: 'nios', abbr: 'NIOS', name: 'National Institute of Open Schooling', levels: 'Open schooling' },
      { id: 'state', abbr: 'State Boards', name: 'Maharashtra, UP, Karnataka, TN, WB & all state boards', levels: 'Class 1–12' },
      { id: 'ncert', abbr: 'NCERT', name: 'NCERT-aligned national curriculum', levels: 'Foundation to senior' },
      { id: 'ib-in', abbr: 'IB', name: 'International Baccalaureate (India schools)', levels: 'PYP · MYP · DP' },
      { id: 'cam-in', abbr: 'Cambridge', name: 'Cambridge International in India', levels: 'IGCSE · AS/A Level' },
    ],
  },
  {
    id: 'international',
    country: 'International',
    flag: '🌐',
    region: 'international',
    accent: 'from-violet-600 to-indigo-700',
    ring: 'ring-violet-200',
    chipBg: 'bg-violet-50 text-violet-900 ring-violet-100',
    boards: [
      { id: 'ib', abbr: 'IB', name: 'International Baccalaureate', levels: 'PYP · MYP · DP · CP' },
      { id: 'igcse', abbr: 'IGCSE', name: 'Cambridge IGCSE', levels: 'Ages 14–16' },
      { id: 'alevel', abbr: 'A Level', name: 'Cambridge International AS & A Level', levels: 'Ages 16–19' },
      { id: 'edexcel-int', abbr: 'Edexcel', name: 'Pearson Edexcel International', levels: 'IGCSE · A Level' },
      { id: 'ap', abbr: 'AP', name: 'Advanced Placement (College Board)', levels: 'Grades 9–12' },
      { id: 'sat', abbr: 'SAT/ACT', name: 'US college entrance preparation', levels: 'Test prep' },
    ],
  },
  {
    id: 'uk',
    country: 'United Kingdom',
    flag: '🇬🇧',
    region: 'europe',
    accent: 'from-blue-700 to-indigo-800',
    ring: 'ring-blue-200',
    chipBg: 'bg-blue-50 text-blue-900 ring-blue-100',
    boards: [
      { id: 'gcse', abbr: 'GCSE', name: 'General Certificate of Secondary Education', levels: 'Ages 14–16' },
      { id: 'gce', abbr: 'A Level', name: 'GCE Advanced Level', levels: 'Ages 16–18' },
      { id: 'cam-uk', abbr: 'Cambridge', name: 'Cambridge Assessment International', levels: 'IGCSE · A Level' },
      { id: 'edexcel-uk', abbr: 'Edexcel', name: 'Pearson Edexcel (UK)', levels: 'GCSE · A Level' },
      { id: 'ocr', abbr: 'OCR', name: 'Oxford, Cambridge and RSA Examinations', levels: 'GCSE · A Level' },
      { id: 'wjec', abbr: 'WJEC', name: 'Welsh Joint Education Committee', levels: 'Wales curriculum' },
      { id: 'sqa', abbr: 'SQA', name: 'Scottish Qualifications Authority', levels: 'Highers · Advanced Highers' },
    ],
  },
  {
    id: 'usa',
    country: 'United States',
    flag: '🇺🇸',
    region: 'americas',
    accent: 'from-red-600 to-blue-700',
    ring: 'ring-red-200',
    chipBg: 'bg-red-50 text-red-900 ring-red-100',
    boards: [
      { id: 'common-core', abbr: 'Common Core', name: 'Common Core State Standards', levels: 'K–12' },
      { id: 'ap-us', abbr: 'AP', name: 'Advanced Placement Program', levels: 'High school' },
      { id: 'ib-us', abbr: 'IB', name: 'International Baccalaureate (US schools)', levels: 'PYP · MYP · DP' },
      { id: 'state-us', abbr: 'State Standards', name: 'California, Texas, NY, Florida & state frameworks', levels: 'K–12' },
      { id: 'honors', abbr: 'Honors', name: 'Honors & gifted tracks', levels: 'Middle & high school' },
    ],
  },
  {
    id: 'uae',
    country: 'UAE & GCC',
    flag: '🇦🇪',
    region: 'middle-east',
    accent: 'from-emerald-600 to-teal-700',
    ring: 'ring-emerald-200',
    chipBg: 'bg-emerald-50 text-emerald-900 ring-emerald-100',
    boards: [
      { id: 'moe-uae', abbr: 'MOE UAE', name: 'UAE Ministry of Education curriculum', levels: 'K–12' },
      { id: 'british-uae', abbr: 'British', name: 'UK National Curriculum (UAE schools)', levels: 'EYFS–A Level' },
      { id: 'american-uae', abbr: 'American', name: 'US curriculum schools in UAE', levels: 'K–12' },
      { id: 'cbse-uae', abbr: 'CBSE', name: 'Indian curriculum (UAE Indian schools)', levels: 'Class 1–12' },
      { id: 'ib-uae', abbr: 'IB', name: 'IB World Schools in UAE', levels: 'PYP · MYP · DP' },
      { id: 'igcse-uae', abbr: 'IGCSE', name: 'Cambridge / Edexcel in GCC', levels: 'O Level · A Level' },
    ],
  },
  {
    id: 'saudi',
    country: 'Saudi Arabia',
    flag: '🇸🇦',
    region: 'middle-east',
    accent: 'from-green-700 to-emerald-800',
    ring: 'ring-green-200',
    chipBg: 'bg-green-50 text-green-900 ring-green-100',
    boards: [
      { id: 'moe-sa', abbr: 'MOE KSA', name: 'Saudi Ministry of Education', levels: 'K–12' },
      { id: 'british-sa', abbr: 'British', name: 'British international schools', levels: 'IGCSE · A Level' },
      { id: 'american-sa', abbr: 'American', name: 'American curriculum schools', levels: 'K–12' },
      { id: 'ib-sa', abbr: 'IB', name: 'International Baccalaureate', levels: 'PYP · MYP · DP' },
    ],
  },
  {
    id: 'qatar',
    country: 'Qatar',
    flag: '🇶🇦',
    region: 'middle-east',
    accent: 'from-rose-700 to-red-800',
    ring: 'ring-rose-200',
    chipBg: 'bg-rose-50 text-rose-900 ring-rose-100',
    boards: [
      { id: 'moe-qa', abbr: 'MOE Qatar', name: 'Qatar Ministry of Education', levels: 'K–12' },
      { id: 'british-qa', abbr: 'British', name: 'UK curriculum international schools', levels: 'IGCSE · A Level' },
      { id: 'ib-qa', abbr: 'IB', name: 'IB programmes in Qatar', levels: 'PYP · MYP · DP' },
      { id: 'american-qa', abbr: 'American', name: 'US curriculum schools', levels: 'K–12' },
    ],
  },
  {
    id: 'singapore',
    country: 'Singapore',
    flag: '🇸🇬',
    region: 'asia-pacific',
    accent: 'from-red-500 to-rose-600',
    ring: 'ring-red-200',
    chipBg: 'bg-rose-50 text-rose-900 ring-rose-100',
    boards: [
      { id: 'sg-gce', abbr: 'GCE', name: 'Singapore-Cambridge GCE O & A Level', levels: 'Secondary · JC' },
      { id: 'ib-sg', abbr: 'IB', name: 'International Baccalaureate', levels: 'PYP · MYP · DP' },
      { id: 'igcse-sg', abbr: 'IGCSE', name: 'Cambridge in Singapore', levels: 'International track' },
    ],
  },
  {
    id: 'malaysia',
    country: 'Malaysia',
    flag: '🇲🇾',
    region: 'asia-pacific',
    accent: 'from-blue-600 to-sky-700',
    ring: 'ring-sky-200',
    chipBg: 'bg-sky-50 text-sky-900 ring-sky-100',
    boards: [
      { id: 'kssr', abbr: 'KSSR/KSSM', name: 'Malaysian national curriculum', levels: 'Primary · Secondary' },
      { id: 'spm', abbr: 'SPM', name: 'Sijil Pelajaran Malaysia', levels: 'Form 5' },
      { id: 'stpm', abbr: 'STPM', name: 'Sijil Tinggi Persekolahan Malaysia', levels: 'Pre-university' },
      { id: 'igcse-my', abbr: 'IGCSE', name: 'Cambridge / international schools', levels: 'O · A Level' },
    ],
  },
  {
    id: 'australia',
    country: 'Australia',
    flag: '🇦🇺',
    region: 'asia-pacific',
    accent: 'from-amber-600 to-yellow-700',
    ring: 'ring-amber-200',
    chipBg: 'bg-amber-50 text-amber-900 ring-amber-100',
    boards: [
      { id: 'acara', abbr: 'ACARA', name: 'Australian Curriculum (national)', levels: 'F–10' },
      { id: 'hsc', abbr: 'HSC', name: 'NSW Higher School Certificate', levels: 'Year 11–12' },
      { id: 'vce', abbr: 'VCE', name: 'Victorian Certificate of Education', levels: 'Year 11–12' },
      { id: 'qce', abbr: 'QCE', name: 'Queensland Certificate of Education', levels: 'Year 11–12' },
      { id: 'wace', abbr: 'WACE', name: 'WA Certificate of Education', levels: 'Year 11–12' },
      { id: 'cam-au', abbr: 'Cambridge', name: 'Cambridge in Australian schools', levels: 'IGCSE · A Level' },
    ],
  },
  {
    id: 'new-zealand',
    country: 'New Zealand',
    flag: '🇳🇿',
    region: 'asia-pacific',
    accent: 'from-slate-600 to-slate-800',
    ring: 'ring-slate-200',
    chipBg: 'bg-slate-100 text-slate-900 ring-slate-200',
    boards: [
      { id: 'ncea', abbr: 'NCEA', name: 'National Certificate of Educational Achievement', levels: 'Levels 1–3' },
      { id: 'cam-nz', abbr: 'Cambridge', name: 'Cambridge International NZ', levels: 'IGCSE · A Level' },
      { id: 'ib-nz', abbr: 'IB', name: 'International Baccalaureate', levels: 'PYP · MYP · DP' },
    ],
  },
  {
    id: 'canada',
    country: 'Canada',
    flag: '🇨🇦',
    region: 'americas',
    accent: 'from-red-600 to-red-700',
    ring: 'ring-red-200',
    chipBg: 'bg-red-50 text-red-900 ring-red-100',
    boards: [
      { id: 'ontario', abbr: 'Ontario', name: 'Ontario Ministry of Education curriculum', levels: 'K–12' },
      { id: 'bc', abbr: 'BC', name: 'British Columbia curriculum', levels: 'K–12' },
      { id: 'alberta', abbr: 'Alberta', name: 'Alberta Education programs of study', levels: 'K–12' },
      { id: 'quebec', abbr: 'Québec', name: 'Quebec education program (CEGEP pathway)', levels: 'K–11 + CEGEP' },
      { id: 'ib-ca', abbr: 'IB', name: 'International Baccalaureate Canada', levels: 'PYP · MYP · DP' },
    ],
  },
  {
    id: 'south-africa',
    country: 'South Africa',
    flag: '🇿🇦',
    region: 'africa',
    accent: 'from-green-600 to-lime-700',
    ring: 'ring-green-200',
    chipBg: 'bg-green-50 text-green-900 ring-green-100',
    boards: [
      { id: 'caps', abbr: 'CAPS', name: 'Curriculum and Assessment Policy Statement', levels: 'Grade R–12' },
      { id: 'ieb', abbr: 'IEB', name: 'Independent Examinations Board', levels: 'Private schools' },
      { id: 'cam-za', abbr: 'Cambridge', name: 'Cambridge International SA', levels: 'IGCSE · AS/A Level' },
      { id: 'nsc', abbr: 'NSC', name: 'National Senior Certificate (matric)', levels: 'Grade 12' },
    ],
  },
  {
    id: 'nigeria',
    country: 'Nigeria',
    flag: '🇳🇬',
    region: 'africa',
    accent: 'from-green-700 to-emerald-800',
    ring: 'ring-emerald-200',
    chipBg: 'bg-emerald-50 text-emerald-900 ring-emerald-100',
    boards: [
      { id: 'waec', abbr: 'WAEC', name: 'West African Examinations Council', levels: 'SSCE' },
      { id: 'neco', abbr: 'NECO', name: 'National Examinations Council', levels: 'SSCE' },
      { id: 'british-ng', abbr: 'British', name: 'British international curriculum', levels: 'IGCSE · A Level' },
      { id: 'cam-ng', abbr: 'Cambridge', name: 'Cambridge in Nigeria', levels: 'IGCSE · A Level' },
    ],
  },
  {
    id: 'kenya',
    country: 'Kenya',
    flag: '🇰🇪',
    region: 'africa',
    accent: 'from-red-600 to-green-700',
    ring: 'ring-amber-200',
    chipBg: 'bg-amber-50 text-amber-900 ring-amber-100',
    boards: [
      { id: 'cbc', abbr: 'CBC', name: 'Competency Based Curriculum (Kenya)', levels: 'Pre-primary–senior' },
      { id: 'knec', abbr: 'KNEC', name: 'Kenya National Examinations Council', levels: 'KCPE · KCSE' },
      { id: 'igcse-ke', abbr: 'IGCSE', name: 'Cambridge international schools', levels: 'O · A Level' },
      { id: 'ib-ke', abbr: 'IB', name: 'International Baccalaureate', levels: 'PYP · MYP · DP' },
    ],
  },
  {
    id: 'france',
    country: 'France',
    flag: '🇫🇷',
    region: 'europe',
    accent: 'from-blue-700 to-blue-900',
    ring: 'ring-blue-200',
    chipBg: 'bg-blue-50 text-blue-900 ring-blue-100',
    boards: [
      { id: 'bac', abbr: 'Baccalauréat', name: 'French national baccalaureate', levels: 'Lycée' },
      { id: 'bfem', abbr: 'DNB', name: 'Diplôme national du brevet', levels: 'Collège' },
      { id: 'lycee-int', abbr: 'Lycée Int.', name: 'International sections & OIB', levels: 'Bilingual tracks' },
    ],
  },
  {
    id: 'germany',
    country: 'Germany',
    flag: '🇩🇪',
    region: 'europe',
    accent: 'from-yellow-500 to-red-600',
    ring: 'ring-yellow-200',
    chipBg: 'bg-yellow-50 text-yellow-900 ring-yellow-100',
    boards: [
      { id: 'abitur', abbr: 'Abitur', name: 'German higher education entrance qualification', levels: 'Gymnasium' },
      { id: 'realschule', abbr: 'Realschule', name: 'Realschule leaving certificate', levels: 'Secondary' },
      { id: 'ib-de', abbr: 'IB', name: 'International Baccalaureate (Germany)', levels: 'PYP · MYP · DP' },
    ],
  },
  {
    id: 'japan',
    country: 'Japan',
    flag: '🇯🇵',
    region: 'asia-pacific',
    accent: 'from-rose-600 to-red-700',
    ring: 'ring-rose-200',
    chipBg: 'bg-rose-50 text-rose-900 ring-rose-100',
    boards: [
      { id: 'mext', abbr: 'MEXT', name: 'Japanese national curriculum (Monbukagakusho)', levels: 'Elementary–senior' },
      { id: 'ib-jp', abbr: 'IB', name: 'International Baccalaureate Japan', levels: 'PYP · MYP · DP' },
      { id: 'cam-jp', abbr: 'Cambridge', name: 'International schools in Japan', levels: 'IGCSE · A Level' },
    ],
  },
  {
    id: 'china',
    country: 'China',
    flag: '🇨🇳',
    region: 'asia-pacific',
    accent: 'from-red-600 to-red-800',
    ring: 'ring-red-200',
    chipBg: 'bg-red-50 text-red-900 ring-red-100',
    boards: [
      { id: 'gaokao', abbr: 'Gaokao', name: 'National College Entrance Examination prep', levels: 'Senior secondary' },
      { id: 'ib-cn', abbr: 'IB', name: 'International Baccalaureate (China)', levels: 'International schools' },
      { id: 'igcse-cn', abbr: 'IGCSE', name: 'Cambridge / British schools in China', levels: 'International track' },
      { id: 'ap-cn', abbr: 'AP', name: 'Advanced Placement (international schools)', levels: 'High school' },
    ],
  },
  {
    id: 'hong-kong',
    country: 'Hong Kong',
    flag: '🇭🇰',
    region: 'asia-pacific',
    accent: 'from-red-500 to-rose-600',
    ring: 'ring-red-200',
    chipBg: 'bg-red-50 text-red-900 ring-red-100',
    boards: [
      { id: 'dse', abbr: 'HKDSE', name: 'Hong Kong Diploma of Secondary Education', levels: 'Secondary 6' },
      { id: 'ib-hk', abbr: 'IB', name: 'International Baccalaureate', levels: 'PYP · MYP · DP' },
      { id: 'igcse-hk', abbr: 'IGCSE', name: 'Cambridge / British curriculum', levels: 'International schools' },
    ],
  },
  {
    id: 'philippines',
    country: 'Philippines',
    flag: '🇵🇭',
    region: 'asia-pacific',
    accent: 'from-blue-600 to-indigo-700',
    ring: 'ring-blue-200',
    chipBg: 'bg-blue-50 text-blue-900 ring-blue-100',
    boards: [
      { id: 'deped', abbr: 'DepEd', name: 'Department of Education K–12 curriculum', levels: 'K–12' },
      { id: 'ib-ph', abbr: 'IB', name: 'International Baccalaureate', levels: 'International schools' },
      { id: 'cam-ph', abbr: 'Cambridge', name: 'Cambridge international programmes', levels: 'IGCSE · A Level' },
    ],
  },
  {
    id: 'indonesia',
    country: 'Indonesia',
    flag: '🇮🇩',
    region: 'asia-pacific',
    accent: 'from-red-500 to-white',
    ring: 'ring-red-200',
    chipBg: 'bg-red-50 text-red-900 ring-red-100',
    boards: [
      { id: 'k13', abbr: 'Kurikulum', name: 'Kurikulum Merdeka / national curriculum', levels: 'SD–SMA' },
      { id: 'cam-id', abbr: 'Cambridge', name: 'Cambridge in Indonesia', levels: 'IGCSE · A Level' },
      { id: 'ib-id', abbr: 'IB', name: 'International Baccalaureate', levels: 'PYP · MYP · DP' },
    ],
  },
  {
    id: 'kuwait',
    country: 'Kuwait',
    flag: '🇰🇼',
    region: 'middle-east',
    accent: 'from-sky-600 to-blue-800',
    ring: 'ring-sky-200',
    chipBg: 'bg-sky-50 text-sky-900 ring-sky-100',
    boards: [
      { id: 'moe-kw', abbr: 'MOE Kuwait', name: 'Kuwait Ministry of Education', levels: 'K–12' },
      { id: 'british-kw', abbr: 'British', name: 'UK curriculum schools', levels: 'IGCSE · A Level' },
      { id: 'american-kw', abbr: 'American', name: 'US curriculum schools', levels: 'K–12' },
      { id: 'cbse-kw', abbr: 'CBSE', name: 'Indian curriculum schools', levels: 'Class 1–12' },
    ],
  },
  {
    id: 'oman',
    country: 'Oman',
    flag: '🇴🇲',
    region: 'middle-east',
    accent: 'from-red-600 to-green-700',
    ring: 'ring-red-200',
    chipBg: 'bg-red-50 text-red-900 ring-red-100',
    boards: [
      { id: 'moe-om', abbr: 'MOE Oman', name: 'Oman Ministry of Education', levels: 'K–12' },
      { id: 'british-om', abbr: 'British', name: 'British international curriculum', levels: 'IGCSE · A Level' },
      { id: 'ib-om', abbr: 'IB', name: 'International Baccalaureate', levels: 'PYP · MYP · DP' },
    ],
  },
  {
    id: 'bahrain',
    country: 'Bahrain',
    flag: '🇧🇭',
    region: 'middle-east',
    accent: 'from-red-600 to-white',
    ring: 'ring-red-200',
    chipBg: 'bg-red-50 text-red-900 ring-red-100',
    boards: [
      { id: 'moe-bh', abbr: 'MOE Bahrain', name: 'Bahrain Ministry of Education', levels: 'K–12' },
      { id: 'british-bh', abbr: 'British', name: 'UK curriculum international schools', levels: 'IGCSE · A Level' },
      { id: 'cbse-bh', abbr: 'CBSE', name: 'Indian curriculum schools', levels: 'Class 1–12' },
    ],
  },
]

export const totalBoardCount = countriesByBoards.reduce((sum, c) => sum + c.boards.length, 0)

export const totalCountryCount = countriesByBoards.length
